stages:
  - test
  - deploy

test:
  stage: test
  script: echo "Realizando pruebas..."
    - pip install pytest pytest-cov
    - pytest --cov=app --cov-report=xml

deploy_production:
  stage: deploy
  script: echo "Implementando en producción..."

deploy_testing:
  stage: deploy
  script: echo "Implementando en testing..."