image: maven:3.6.1-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GITLAB_PERSONAL_TOKEN: "glpat-9g1Sxf414k7TdBE2Xs93"

cache:
  paths:
    - .m2/repository/
    - target/

test_coverage:
  stage: test
  script:
    - mvn clean test $MAVEN_CLI_OPTS
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml

deploy_production:
  stage: deploy
  script:
    - mvn clean deploy $MAVEN_CLI_OPTS
  only:
    - master

test_coverage_QA:
  stage: test
  script:
    - mvn clean test $MAVEN_CLI_OPTS
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
  only:
    - QA