stages:
  - build
  - test
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn clean package"
  artifacts:
    paths:
      - target/*.jar

maven-test:
  image: maven:3-jdk-8
  stage: test
  script: "mvn test"
  dependencies:
    - maven-build

deploy-production:
  image: postgres:latest
  stage: deploy
  script:
    - cp target/myapp.jar myapp.jar
    - java -jar myapp.jar
  when: manual
  only:
    - master