image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: biblioteca

before_script:
  - docker login -u "viafarajm" -p "Sebas1774" docker.io

build:
  stage: build
  script:
    - docker build -t "biblioteca" .
    - docker push "biblioteca"