version: '3.8'

services:
  app_testing:
    build:
      context: .
      dockerfile: Dockerfile.testing
    image: myproject-testing:latest
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
    depends_on:
      - db_testing

  db_testing:
    image: postgres:13
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB